In [2]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-0.3.2-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: packaging in c:\users\ghada\anaconda3\lib\site-packages (from kagglehub) (23.2)
Requirement already satisfied: requests in c:\users\ghada\anaconda3\lib\site-packages (from kagglehub) (2.32.2)
Requirement already satisfied: tqdm in c:\users\ghada\anaconda3\lib\site-packages (from kagglehub) (4.66.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ghada\anaconda3\lib\site-packages (from requests->kagglehub) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ghada\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ghada\anaconda3\lib\site-packages (from requests->kagglehub) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ghada\anaconda3\lib\site-packages (from requests->kagglehub) (2024.8.30)
Requirement already satisfied: colorama in c:\users\ghada\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-0.3.2-py3-none-any.whl (42 kB)
   ---------------------------------------- 0.0/42.8 kB ? eta -:--:--
   --------- ------------------------------ 10.2/42.8 kB ? eta -:--:--
   -------------------------------------- - 41.0/42.8 kB 487.6 kB/s eta 0:00:01
   ---------------------------------------- 42.8/42.8 kB 417.4 kB/s eta 0:00:00
Installing collected packages: kagglehub
Successfully installed kagglehub-0.3.2

In [81]:
#Import all relevant libraries
import kagglehub
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import zscore
import os
 
## This statement allows the visuals to render within your Jupyter Notebook.
%matplotlib inline

## Loading the data
We can now load the dataset into pandas using the read_csv() function. This converts the CSV file into a Pandas dataframe.

In [85]:
folder_path = kagglehub.dataset_download("unsdsn/world-happiness")
files = os.listdir(folder_path)

In [130]:
#Read in the csv file and convert to a Pandas dataframe
os.listdir(folder_path)
dataframes = {}

for file in files:
    file_path = os.path.join(folder_path, file)
    if os.path.isfile(file_path): 
        df = pd.read_csv(file_path)
        dataframes[file] = df

In [128]:
df_2015 = dataframes[list(dataframes.keys())[0]]
df_2016 = dataframes[list(dataframes.keys())[1]]
df_2017 = dataframes[list(dataframes.keys())[2]]
df_2018 = dataframes[list(dataframes.keys())[3]]
df_2019 = dataframes[list(dataframes.keys())[4]]

In [294]:
merged_df = pd.concat([df_2015,df_2016,df_2017,df_2018,df_2019], axis=1) # concat all dataframes on columns

### Viewing the dataframe
We can get a quick sense of the size of our dataset by using the shape method. This returns a tuple with the number of rows and columns in the dataset.

In [297]:
merged_df.shape

(158, 55)

In [302]:
merged_df.sample(5)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),...,Perceptions of corruption,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
141,Senegal,Sub-Saharan Africa,142,3.904,0.03608,0.36498,0.97619,0.43540,0.36772,0.10713,...,0.061,142.0,Comoros,3.973,0.274,0.757,0.505,0.142,0.275,0.078
106,Tunisia,Middle East and Northern Africa,107,4.739,0.03589,0.88113,0.60429,0.73793,0.26268,0.06358,...,0.103,107.0,Albania,4.719,0.947,0.848,0.874,0.383,0.178,0.027
49,Italy,Western Europe,50,5.948,0.03914,1.25114,1.19777,0.95446,0.26236,0.02901,...,0.006,50.0,Ecuador,6.028,0.912,1.312,0.868,0.498,0.126,0.087
130,Malawi,Sub-Saharan Africa,131,4.292,0.06130,0.01604,0.41134,0.22562,0.43054,0.06977,...,0.060,131.0,Myanmar,4.360,0.710,1.181,0.555,0.525,0.566,0.172
86,Serbia,Central and Eastern Europe,87,5.123,0.04864,0.92053,1.00964,0.74836,0.20107,0.02617,...,0.176,87.0,Turkmenistan,5.247,1.052,1.538,0.657,0.394,0.244,0.028

## 1. Data Profiling:
Data profiling is a comprehensive process of examining the data available in an existing dataset and collecting statistics and information about that data.

In [305]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 55 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
 12  Country                        157 non-null    object
 13  Region                         157 non-null    object
 14  Happiness Rank                 157 non-null    float64
 15  Happiness Score                157 non-null    float64
 16  Lower Confidence Interval      157 non-null    float64
 17  Upper Confidence Interval      157 non-null    float64
 18  Economy (GDP per Capita)       157 non-null    float64
 19  Family                         157 non-null    float64
 20  Health (Life Expectancy)       157 non-null    float64
 21  Freedom                        157 non-null    float64
 22  Trust (Government Corruption)  157 non-null    float64
 23  Generosity                     157 non-null    float64
 24  Dystopia Residual              157 non-null    float64
 25  Country                        155 non-null    object
 26  Happiness.Rank                 155 non-null    float64
 27  Happiness.Score                155 non-null    float64
 28  Whisker.high                   155 non-null    float64
 29  Whisker.low                    155 non-null    float64
 30  Economy..GDP.per.Capita.       155 non-null    float64
 31  Family                         155 non-null    float64
 32  Health..Life.Expectancy.       155 non-null    float64
 33  Freedom                        155 non-null    float64
 34  Generosity                     155 non-null    float64
 35  Trust..Government.Corruption.  155 non-null    float64
 36  Dystopia.Residual              155 non-null    float64
 37  Overall rank                   156 non-null    float64
 38  Country or region              156 non-null    object
 39  Score                          156 non-null    float64
 40  GDP per capita                 156 non-null    float64
 41  Social support                 156 non-null    float64
 42  Healthy life expectancy        156 non-null    float64
 43  Freedom to make life choices   156 non-null    float64
 44  Generosity                     156 non-null    float64
 45  Perceptions of corruption      155 non-null    float64
 46  Overall rank                   156 non-null    float64
 47  Country or region              156 non-null    object
 48  Score                          156 non-null    float64
 49  GDP per capita                 156 non-null    float64
 50  Social support                 156 non-null    float64
 51  Healthy life expectancy        156 non-null    float64
 52  Freedom to make life choices   156 non-null    float64
 53  Generosity                     156 non-null    float64
 54  Perceptions of corruption      156 non-null    float64
dtypes: float64(47), int64(1), object(7)
memory usage: 68.0+ KB

In [307]:
df.shape

(156, 9)

In [313]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Overall rank,156.0,NaN,NaN,NaN,78.5,45.177428,1.0,39.75,78.5,117.25,156.0
Country or region,156,156,Finland,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Score,156.0,NaN,NaN,NaN,5.407096,1.11312,2.853,4.5445,5.3795,6.1845,7.769
GDP per capita,156.0,NaN,NaN,NaN,0.905147,0.398389,0.0,0.60275,0.96,1.2325,1.684
Social support,156.0,NaN,NaN,NaN,1.208814,0.299191,0.0,1.05575,1.2715,1.4525,1.624
Healthy life expectancy,156.0,NaN,NaN,NaN,0.725244,0.242124,0.0,0.54775,0.789,0.88175,1.141
Freedom to make life choices,156.0,NaN,NaN,NaN,0.392571,0.143289,0.0,0.308,0.417,0.50725,0.631
Generosity,156.0,NaN,NaN,NaN,0.184846,0.095254,0.0,0.10875,0.1775,0.24825,0.566
Perceptions of corruption,156.0,NaN,NaN,NaN,0.110603,0.094538,0.0,0.047,0.0855,0.14125,0.453

In [315]:
merged_df.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Country', 'Region',
       'Happiness Rank', 'Happiness Score', 'Lower Confidence Interval',
       'Upper Confidence Interval', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Country', 'Happiness.Rank',
       'Happiness.Score', 'Whisker.high', 'Whisker.low',
       'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.',
       'Freedom', 'Generosity', 'Trust..Government.Corruption.',
       'Dystopia.Residual', 'Overall rank', 'Country or region', 'Score',
       'GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Overall rank', 'Country or region',
       'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

The process of profiling differs slightly for categorical and numerical variables due to their inherent differences.

**The two main types of data are:**
- Quantitative (numerical) data
- Qualitative (categorical) data

### Data Quality Checks
Data quality checks involve the process of ensuring that the data is accurate, complete, consistent, relevant, and reliable. 


**Here are typical steps involved in checking data quality:**

#### 1. Reliability:
Evaluate the data's source and collection process to determine its trustworthiness.

In [320]:
# its taken from Gallup World Poll

#### 2. Timeliness: 
Ensure the data is up-to-date and reflective of the current situation or the period of interest for the analysis.

In [323]:
# its taken from 2015 to 2019

#### 3. Consistency: 

Confirm that the data is consistent within the dataset and across multiple data sources. For example, the same data point should not have different values in different places.

In [326]:
merged_df

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),...,Perceptions of corruption,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,...,0.393,1.0,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,...,0.340,2.0,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,...,0.408,3.0,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,...,0.138,4.0,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,...,0.357,5.0,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,...,0.106,154.0,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,...,0.038,155.0,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,...,0.076,156.0,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [328]:
# after we have merged the files into one data frame (merged_df)
#  there is inconsistency with the data, Country column, Region column with Country or region column

#### 4. Relevance: 
Assess whether the data is appropriate and applicable for the intended analysis. Data that is not relevant can skew results and lead to incorrect conclusions.

**Key considerations for relevance include:**

> 1. Sample Appropriateness: Confirm that your data sample aligns with your analysis objectives. For instance, utilizing data from the Northern region will not yield accurate insights for the Western region of the Kingdom.
>
> 2. Variable Selection: Any column will not be relevant for our analysis, we can get rid of these using the drop() method. We will set the “axis” argument to 1 since we’re dealing with columns, and set the “inplace” argument to True to make the change permanent.

In [331]:
# all columns are important to the study, there are not unnecessary columns

#### 5. Uniqueness: 
Check for and remove duplicate records to prevent skewed analysis results.

In [334]:
merged_df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),...,Perceptions of corruption,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,...,0.393,1.0,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,...,0.340,2.0,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,...,0.408,3.0,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,...,0.138,4.0,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,...,0.357,5.0,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [336]:
merged_df.duplicated().sum()

0

In [338]:
merged_df.isnull().sum()

Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Standard Error                   0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
Country                          1
Region                           1
Happiness Rank                   1
Happiness Score                  1
Lower Confidence Interval        1
Upper Confidence Interval        1
Economy (GDP per Capita)         1
Family                           1
Health (Life Expectancy)         1
Freedom                          1
Trust (Government Corruption)    1
Generosity                       1
Dystopia Residual                1
Country                          3
Happiness.Rank                   3
Happiness.Score                  3
Whisker.high                     3
Whisker.low                      3
Economy..GDP.per.Capita.         3
Family                           3
Health..Life.Expectancy.         3
Freedom                          3
Generosity                       3
Trust..Government.Corruption.    3
Dystopia.Residual                3
Overall rank                     2
Country or region                2
Score                            2
GDP per capita                   2
Social support                   2
Healthy life expectancy          2
Freedom to make life choices     2
Generosity                       2
Perceptions of corruption        3
Overall rank                     2
Country or region                2
Score                            2
GDP per capita                   2
Social support                   2
Healthy life expectancy          2
Freedom to make life choices     2
Generosity                       2
Perceptions of corruption        2
dtype: int64

In [340]:
merged_df[merged_df.duplicated()]

Empty DataFrame
Columns: [Country, Region, Happiness Rank, Happiness Score, Standard Error, Economy (GDP per Capita), Family, Health (Life Expectancy), Freedom, Trust (Government Corruption), Generosity, Dystopia Residual, Country, Region, Happiness Rank, Happiness Score, Lower Confidence Interval, Upper Confidence Interval, Economy (GDP per Capita), Family, Health (Life Expectancy), Freedom, Trust (Government Corruption), Generosity, Dystopia Residual, Country, Happiness.Rank, Happiness.Score, Whisker.high, Whisker.low, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., Dystopia.Residual, Overall rank, Country or region, Score, GDP per capita, Social support, Healthy life expectancy, Freedom to make life choices, Generosity, Perceptions of corruption, Overall rank, Country or region, Score, GDP per capita, Social support, Healthy life expectancy, Freedom to make life choices, Generosity, Perceptions of corruption]
Index: []

[0 rows x 55 columns]

In [342]:
# go to delete duplicates columns
# there are no duplicated rows or columns

#### 6. Completeness: 
Ensure that no critical data is missing. This might mean checking for null values or required fields that are empty.

We will start by checking the dataset for missing or null values. For this, we can use the isna() method which returns a dataframe of boolean values indicating if a field is null or not. To group all missing values by column, we can include the sum() method.

In [345]:
#Display number missing values per column
merged_df.isnull().sum().sort_values(ascending = False)

Happiness.Score                  3
Whisker.low                      3
Economy..GDP.per.Capita.         3
Happiness.Rank                   3
Country                          3
Family                           3
Health..Life.Expectancy.         3
Freedom                          3
Generosity                       3
Trust..Government.Corruption.    3
Dystopia.Residual                3
Whisker.high                     3
Perceptions of corruption        3
Freedom to make life choices     2
Country or region                2
Generosity                       2
Freedom to make life choices     2
Healthy life expectancy          2
Social support                   2
GDP per capita                   2
Score                            2
Overall rank                     2
Healthy life expectancy          2
Overall rank                     2
Country or region                2
Score                            2
GDP per capita                   2
Generosity                       2
Social support                   2
Perceptions of corruption        2
Region                           1
Economy (GDP per Capita)         1
Country                          1
Dystopia Residual                1
Happiness Rank                   1
Happiness Score                  1
Upper Confidence Interval        1
Lower Confidence Interval        1
Family                           1
Health (Life Expectancy)         1
Freedom                          1
Trust (Government Corruption)    1
Generosity                       1
Family                           0
Happiness Rank                   0
Happiness Score                  0
Standard Error                   0
Economy (GDP per Capita)         0
Region                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
Country                          0
dtype: int64

In [347]:
# go to clean them 
# clean only full missing rows
merged_df.dropna(inplace=True)

#### 7. Check Accuracy:

Verify that the data is correct and precise. This could involve comparing data samples with known sources or using validation rules.

**The process includes:**
1. Validating the appropriateness of data types for the dataset.
2. Identifying outliers  using established validation  rule

In [2]:
# check columns types

In [33]:
# go to clean them

In [3]:
# check outliers

**What is an Outlier?** 
Outlier is an row/observation that appears far away and diverges from an overall pattern in a sample.

**What are the types of Outliers?**
1. Univariate: These outliers can be found when we look at distribution of a single variable
2. Multivariate: are outliers in an n-dimensional space. In order to find them, you have to look at distributions in multi-dimensions. example (hight=100, weight=100) for a person

**What causes Outliers?**
Whenever we come across outliers, the ideal way to tackle them is to find out the reason of having these outliers. The method to deal with them would then depend on the reason of their occurrence.

Let’s understand various types of outliers:

1. Data Entry Errors:- Human errors such as errors caused during data collection, recording, or entry can cause outliers in data.
2. Measurement Error: It is the most common source of outliers. This is caused when the measurement instrument used turns out to be faulty.
3. Data Processing Error: Whenever we perform data mining, we extract data from multiple sources. It is possible that some manipulation or extraction errors may lead to outliers in the dataset.
4. Sampling error: For instance, we have to measure the height of athletes. By mistake, we include a few basketball players in the sample. This inclusion is likely to cause outliers in the dataset.
5. Natural Outlier: When an outlier is not artificial (due to error), it is a natural outlier. For instance: In my last assignment with one of the renowned insurance company, I noticed that the performance of top 50 financial advisors was far higher than rest of the population. Surprisingly, it was not due to any error. Hence, whenever we perform any data mining activity with advisors, we used to treat this segment separately.


**What is the impact of Outliers on a dataset?**


![image.png](https://www.analyticsvidhya.com/wp-content/uploads/2015/02/Outlier_31.png)



**How to detect Outliers?**

1. Most commonly used method to detect outliers is visualization (Univariate Graphical Analysis).

We use 3 common visualization methods:
>- Box-plot: A box plot is a method for graphically depicting groups of numerical data through their quartiles. The box extends from the Q1 to Q3 quartile values of the data, with a line at the median (Q2). The whiskers extend from the edges of the box to show the range of the data. Outlier points are those past the end of the whiskers. Box plots show robust measures of location and spread as well as providing information about symmetry and outliers.
>
>  
>![image.png](https://miro.medium.com/v2/resize:fit:698/format:webp/1*VK5iHA2AB28HSZwWwUbNYg.png)
>
>
>- Histogram
>- Scatter Plot: A scatter plot is a mathematical diagram using Cartesian coordinates to display values for two variables for a set of data. The data are displayed as a collection of points, each having the value of one variable determining the position on the horizontal axis and the value of the other variable determining the position on the vertical axis. The points that are far from the population can be termed as an outlier.
>
>  
>![image.png](https://miro.medium.com/v2/resize:fit:4800/format:webp/1*Ov6aH-8yIwNoUxtMFwgx4g.png)
>
>

2. Using statistical method (Univariate Non-Graphical analysis):
>- Any value, which is beyond the range of -1.5 x IQR to 1.5 x IQR
 
![image.png](https://www.whatissixsigma.net/wp-content/uploads/2015/07/Box-Plot-Diagram-to-identify-Outliers-figure-1.png)

>- Use capping methods. Any value which out of range of 5th and 95th percentile can be considered as outlier
>- Data points, three or more standard deviation away from mean are considered outlier: The Z-score is the signed number of standard deviations by which the value of an observation or data point is above the mean value of what is being observed or measured. While calculating the Z-score we re-scale and center the data and look for data points that are too far from zero. These data points which are way too far from zero will be treated as the outliers. In most of the cases, a threshold of 3 or -3 is used i.e if the Z-score value is greater than or less than 3 or -3 respectively, that data point will be identified as outliers.
> - Outlier detection is merely a special case of the examination of data for influential data points and it also depends on the business understanding

In [23]:
# go to univariate graphical analysis
# go to lesson : data visualisation 1 - chart type section
# then go to univariate graphical analysis
# detect outliers using graphs varbaly

In [24]:
# go to lesson: statistics 1 then statistics 3
# then go to univariate Non graphical analysis
# detect outliers using numerical statistics

In [25]:
# go to delete ouliers

## 2. Data Cleaning: 

Preliminary findings from data profiling can lead to cleaning the data by:
- Handling missing values
- Correcting errors.
- Dealing with outliers.

-------------------

### Handling missing values:

**Why my data has missing values?**
They may occur at two stages:
1. Data Extraction: It is possible that there are problems with extraction process. Errors at data extraction stage are typically easy to find and can be corrected easily as well.
2. Data collection: These errors occur at time of data collection and are harder to correct.

**Why do we need to handle the missing data?**
To avoid:
- Bias the conclusions.
- Leading the business to make wrong decisions.

**Which are the methods to treat missing values ?**
1. Deletion: we delete rows where any of the variable is missing. Simplicity is one of the major advantage of this method, but this method reduces the power of model because it reduces the sample size.

2. Imputation: is a method to fill in the missing values with estimated ones. This imputation is one of the most frequently used methods.

    2.1. Mean/ Mode/ Median Imputation: It consists of replacing the missing data for a given attribute by the mean or median (quantitative attribute) or mode (qualitative attribute) of all known values of that variable.
    > It can be of two types:
    > - Generalized Imputation: In this case, we calculate the mean or median for all non missing values of that variable then replace missing value with mean or median.
    > - Similar case Imputation: In this case, we calculate average for each group individually of non missing values then replace the missing value based on the group.

    2.2. Constant Value
   
    2.3. Forward Filling
   
    2.4. Backward Filling

6. Prediction Model:  Prediction model is one of the sophisticated method for handling missing data. Here, we create a predictive model to estimate values that will substitute the missing data.  In this case, we divide our data set into two sets: One set with no missing values for the variable and another one with missing values. First data set become training data set of the model while second data set with missing values is test data set and variable with missing values is treated as target variable. Next, we create a model to predict target variable based on other attributes of the training data set and populate missing values of test data set.

> There are 2 drawbacks for this approach:
> - The model estimated values are usually more well-behaved than the true values
> - If there are no relationships with attributes in the data set and the attribute with missing values, then the model will not be precise for estimating missing values.

9. KNN Imputation: In this method of imputation, the missing values of an attribute are imputed using the given number of attributes that are most similar to the attribute whose values are missing. The similarity of two attributes is determined using a distance function. It is also known to have certain advantage & disadvantages.

   > **Advantages:**
   > - k-nearest neighbour can predict both qualitative & quantitative attributes
   > - Creation of predictive model for each attribute with missing data is not required
   > - Attributes with multiple missing values can be easily treated
   > - Correlation structure of the data is taken into consideration

   > **Disadvantage:**
   > - KNN algorithm is very time-consuming in analyzing large database. It searches through all the dataset looking for the most similar instances.
   > - Choice of k-value is very critical. Higher value of k would include attributes which are significantly different from what we need whereas lower value of k implies missing out of significant attributes.

--------------------

In [80]:
# go back to 6th dimention --> Completeness

### Correcting errors

-------------------

In [ ]:
# go back to 7th dimension Accuracy

### Dealing with outliers:

**How to remove Outliers?**
Most of the ways to deal with outliers are similar to the methods of missing values like deleting rows, transforming them, binning them, treat them as a separate group, imputing values and other statistical methods. Here, we will discuss the common techniques used to deal with outliers:

1. Deleting rows: We delete outlier values if it is due to data entry error, data processing error or outlier rows are very small in numbers. We can also use trimming at both ends to remove outliers.

2. Imputing: Like imputation of missing values, we can also impute outliers. We can use mean, median, mode imputation methods. Before imputing values, we should analyse if it is natural outlier or artificial. If it is artificial, we can go with imputing values. We can also use statistical model to predict values of outlier rows and after that we can impute it with predicted values.

3. Treat separately: If there are significant number of outliers, we should treat them separately in the statistical model. One of the approach is to treat both groups as two different groups and build individual model for both groups and then combine the output.

## 3. Univariate Analysis: 

This involves examining single variables to understand their characteristics (distribution, central tendency, dispersion, and shape).

We calculate **numerical values** about the data that tells us about the distribution of the data. We also **draw graphs** showing visually how the data is distributed. **To answer the following questions about Features/characteristics of Data:**
- Where is the center of the data? (location)
- How much does the data vary? (scale)
- What is the shape of the data? (shape)

**The benefits of this analysis:**
Statistics summary gives a high-level idea to identify whether the data has any outliers, data entry error, distribution of data such as the data is normally distributed or left/right skewed

**In this step, we will explore variables one by one using following approaches:**

### 1. Univariate Graphical Analysis:
Method to perform uni-variate analysis will depend on whether the variable type is categorical or numerical.

#### I. Categorical Variables:

we’ll use frequency table to understand distribution of each category
- Bar Chart (Ordinal) - Orderd
- Pie Chart (Nominal) - non Orderd

#### II. Numerical Variables:

we need to understand the central tendency and spread of the variable (Descriptive Analysis) using:
   - Box plot
   - Histogram

### 2. Univariate Non-Graphical analysis: 

- Where is the center of the data? (location) --> **Measures of central tendency**
- How much does the data vary? (scale) --> **Measure of variability**
- What is the shape of the data? (shape) --> **Measures of variation combined with an average (measure of center) gives a good picture of the distribution of the data.**

## 4. Bivariate/Multivariate Analysis:

Here, you look at the relationships between two or more variables. This can involve looking for correlations, patterns, and trends that suggest a relationship or an association.

We can perform bi-variate analysis for any combination of categorical and numerical variables. The combination can be:
| bi-variate variables   | Plot type |
| ------------- | ------------- |
| Categorical & Categorical| Stacked Bar Chart |
| Categorical & numerical  | scatter plot, histogram, box plot|
| numerical  & numerical  | Scatter plot, line chart| 


Multivariate Analysis:
- Heat map
- Bar Chart
- Scatter Chart
- Line Chart

**Categorical & Categorical --> (Stacked Column Chart)**

**Categorical & numerical --> (scatter plot, histogram, box plot)**

**numerical & numerical --> (Scatter plot, line chart)**

We could also use a correlation matrix to get more specific information about the relationship between these two variables.